# H9 II USB PCM 0 = Chat; PCM 1 = Game.
{
  "monitor.alsa.rules": [
    {
      "matches": [
        {
          "device.name": "alsa_card.usb-Sony_INZONE_H9_II-00"
        }
      ],
      "actions": {
        "update-props": {
          "device.profile-set": "usb-gaming-headset.conf",
          "device.profile": "output:stereo-game+output:stereo-chat+input:mono-chat"
        }
      }
    },
    {
      "matches": [
        {
          "node.name": "alsa_output.usb-Sony_INZONE_H9_II-00.stereo-game"
        }
      ],
      "actions": {
        "update-props": {
          "node.description": "INZONE H9 II - Game",
          "node.nick": "INZONE H9 II - Game",
          "priority.session": 1450
        }
      }
    },
    {
      "matches": [
        {
          "node.name": "alsa_output.usb-Sony_INZONE_H9_II-00.stereo-chat"
        }
      ],
      "actions": {
        "update-props": {
          "node.description": "INZONE H9 II - Chat",
          "node.nick": "INZONE H9 II - Chat",
          "priority.session": 1000
        }
      }
    },
    {
      "matches": [
        {
          "node.name": "alsa_input.usb-Sony_INZONE_H9_II-00.mono-chat"
        }
      ],
      "actions": {
        "update-props": {
          "node.description": "INZONE H9 II - Microphone",
          "node.nick": "INZONE H9 II - Microphone",
          "priority.session": 1400
        }
      }
    }
  ]
}
