# INZONE profile: fps
{
  "monitor.alsa.rules": [
    {
      "matches": [
        {
          "node.name": "~alsa_output[.]usb-Sony_INZONE_H9_II-00[.].*"
        }
      ],
      "actions": {
        "update-props": {
          "audio.rate": 48000,
          "node.latency": "128/48000",
          "priority.session": 1400,
          "session.suspend-timeout-seconds": 0
        }
      }
    },
    {
      "matches": [
        {
          "node.name": "~alsa_input[.]usb-Sony_INZONE_H9_II-00[.].*"
        }
      ],
      "actions": {
        "update-props": {
          "audio.rate": 48000,
          "node.latency": "256/48000"
        }
      }
    }
  ],
  "node.filter-graph.rules": [
    {
      "matches": [
        {
          "node.name": "~alsa_output[.]usb-Sony_INZONE_H9_II-00[.].*"
        }
      ],
      "actions": {
        "create-filter-graph": [
          "{\"nodes\":[{\"type\":\"builtin\",\"name\":\"preamp\",\"label\":\"linear\",\"control\":{\"Mult\":0.7079457843841379,\"Add\":0.0}},{\"type\":\"builtin\",\"name\":\"eq0\",\"label\":\"bq_lowshelf\",\"control\":{\"Freq\":150.0,\"Q\":0.707,\"Gain\":-4.0}},{\"type\":\"builtin\",\"name\":\"eq1\",\"label\":\"bq_peaking\",\"control\":{\"Freq\":2500.0,\"Q\":0.8,\"Gain\":2.0}}],\"links\":[{\"output\":\"preamp:Out\",\"input\":\"eq0:In\"},{\"output\":\"eq0:Out\",\"input\":\"eq1:In\"}],\"inputs\":[\"preamp:In\"],\"outputs\":[\"eq1:Out\"]}"
        ]
      }
    }
  ]
}
