# INZONE profile: music
{
  "monitor.alsa.rules": [
    {
      "matches": [
        {
          "node.name": "~alsa_output[.]usb-Sony_INZONE_H9_II-00[.].*"
        }
      ],
      "actions": {
        "update-props": {
          "audio.rate": 48000,
          "node.latency": "512/48000",
          "priority.session": 1400,
          "session.suspend-timeout-seconds": 5,
          "dither.method": "triangular",
          "resample.quality": 14
        }
      }
    },
    {
      "matches": [
        {
          "node.name": "~alsa_input[.]usb-Sony_INZONE_H9_II-00[.].*"
        }
      ],
      "actions": {
        "update-props": {
          "audio.rate": 48000,
          "node.latency": "256/48000"
        }
      }
    }
  ],
  "node.filter-graph.rules": []
}
