# INZONE profile: voice
{
  "monitor.alsa.rules": [
    {
      "matches": [
        {
          "node.name": "~alsa_output[.]usb-Sony_INZONE_H9_II-00[.].*"
        }
      ],
      "actions": {
        "update-props": {
          "audio.rate": 48000,
          "node.latency": "256/48000",
          "priority.session": 1400,
          "session.suspend-timeout-seconds": 0
        }
      }
    },
    {
      "matches": [
        {
          "node.name": "~alsa_input[.]usb-Sony_INZONE_H9_II-00[.].*"
        }
      ],
      "actions": {
        "update-props": {
          "audio.rate": 48000,
          "node.latency": "256/48000"
        }
      }
    }
  ],
  "node.filter-graph.rules": [
    {
      "matches": [
        {
          "node.name": "~alsa_output[.]usb-Sony_INZONE_H9_II-00[.].*"
        }
      ],
      "actions": {
        "create-filter-graph": [
          "{\"nodes\":[{\"type\":\"builtin\",\"name\":\"preamp\",\"label\":\"linear\",\"control\":{\"Mult\":0.7943282347242815,\"Add\":0.0}},{\"type\":\"builtin\",\"name\":\"eq0\",\"label\":\"bq_lowshelf\",\"control\":{\"Freq\":180.0,\"Q\":0.707,\"Gain\":-3.0}},{\"type\":\"builtin\",\"name\":\"eq1\",\"label\":\"bq_peaking\",\"control\":{\"Freq\":1800.0,\"Q\":0.8,\"Gain\":1.5}},{\"type\":\"builtin\",\"name\":\"eq2\",\"label\":\"bq_highshelf\",\"control\":{\"Freq\":7000.0,\"Q\":0.707,\"Gain\":-2.0}}],\"links\":[{\"output\":\"preamp:Out\",\"input\":\"eq0:In\"},{\"output\":\"eq0:Out\",\"input\":\"eq1:In\"},{\"output\":\"eq1:Out\",\"input\":\"eq2:In\"}],\"inputs\":[\"preamp:In\"],\"outputs\":[\"eq2:Out\"]}"
        ]
      }
    },
    {
      "matches": [
        {
          "node.name": "~alsa_input[.]usb-Sony_INZONE_H9_II-00[.].*"
        }
      ],
      "actions": {
        "create-filter-graph": [
          "{\"nodes\":[{\"type\":\"builtin\",\"name\":\"eq0\",\"label\":\"bq_highpass\",\"control\":{\"Freq\":80.0,\"Q\":0.707,\"Gain\":0.0}}],\"links\":[],\"inputs\":[\"eq0:In\"],\"outputs\":[\"eq0:Out\"]}"
        ]
      }
    }
  ]
}
